prefix = /usr
exec_prefix = $(prefix)
sbindir = $(exec_prefix)/sbin
bindir = $(prefix)/bin
datadir = $(prefix)/share
mandir = $(datadir)/man
sysconfdir = $(prefix)/etc
OPT_CFLAGS = -O2 -g
OPT_CXXFLAGS = -O2 -g
ADB_NOMMU = true
